### ISSUE TITLE
Normal flips, bad mesh display

### ISSUE THREAD

**Issue by AndriyOrlov** [BlenderHQ/path_tool#5]
The normals are flipped, the mesh display is bad, the flipped normals remain in all meshes and when creating new normals are also flipped, I cannot remove the gray display of the mesh and in general it would be better not to display the object like this, it is better by default

https://github.com/BlenderHQ/path_tool/assets/73847765/7353653a-86e4-413a-b21e-bf07a77abe0b

**Comment by ivan-perevala** [comment]
@DeadSue Thanks for the report. Unfortunately, I was unable to reproduce the behavior shown in the video. One thing I can do to help, given the small amount of information provided, is to load Blender with factory-startup settings (```File > Defaults > Load Factory Startup```) (as it could also be one of the other installed addons) and try to repeat the operations shown in the video.

Also, as the person who wrote Path Tool, I would like to add that the addon does not change either the scene display parameters or the normals of the objects it works with. So I would be really interested if you find out the reason, to learn about it. It is quite possible that it will be necessary to contact the developers of another addon, if the reason lies in it.

I am attaching a video of an attempt to reproduce the behavior of the addon.

https://github.com/BlenderHQ/path_tool/assets/16822993/2ff56743-9980-43c7-b051-c278836643b2

The object on the left - with inverted normals, on the right - with normal ones.

![image](https://github.com/BlenderHQ/path_tool/assets/16822993/fc126706-4edc-43f8-8c11-9eb9dd72431f)


Respectfully, Ivan.

**Comment by AndriyOrlov** [comment]
did not help, addon version 3,4,1, the latest, I did as you wrote but it was not enough, blender version 3,6,2 

https://github.com/BlenderHQ/path_tool/assets/73847765/9d674a3f-82d5-4895-91bf-e91a9da3a763

**Comment by ivan-perevala** [comment]
Perfectly! I checked the specified versions, the bug really appeared. Debugging showed that the problem is that newer versions of Blender (and I initially tested on 3.6.0) no longer reconfigure OpenGL state in the viewport (which is quite strange because it should be). Specifically, the problem was at ```path_tool-3_4_1\lib\bhqab\utils_gpu\draw_framework\_aa_base.py > AABase._setup_gpu_state```

```py
gpu.state.front_facing_set(True)
```

As you can see in the screenshot, the normals are actually rotated as they should, but the polygons are displayed rotated because of front facing is still set as true.

![image](https://github.com/BlenderHQ/path_tool/assets/16822993/2ceb0700-04c0-49da-9ac5-a23dd1881027)

I will soon release an update that fixes this flaw. It's a shame that I just couldn't find the Blender commit that created it.

**Comment by AndriyOrlov** [comment]
it's great, but the fact is that this same bug appears for me on version 3,3,9 and subsequent meshes that are created have inverted normals

**Comment by ivan-perevala** [comment]
Perhaps the problem appeared with the ``bhqab'' update. Since I checked now on 3.3.1 and on 3.3.9 - the result is the same. [post by BF](https://code.blender.org/2020/02/release-planning-2020-2025) says that LTS versions get the same fixes (which in theory could cause the problem), but if on in older versions, the problem persists, it is obvious that the problem is here and only here.

And as for
> subsequent meshes that are created have inverted normals

then no, I don't agree. Here the problem is only with the display of everything in the viewport. Object data remain unchanged. This can be seen if you save the file, close Blender and then open this file again.

**Comment by ivan-perevala** [comment]
Anyway, thanks for the report.

Regards, Ivan.
